### ISSUE TITLE
Table "users" not found;

### ISSUE THREAD

**Issue by yaghmr** [fernandezpablo85/slick-production-tips#1]
I've replaced postgres with H2 and I get the error:

error (run-main) org.h2.jdbc.JdbcSQLException: Table "users" not found; SQL statement:
error INSERT INTO "users" ("name","last_name") VALUES (?,?) [42102-166]
org.h2.jdbc.JdbcSQLException: Table "users" not found; SQL statement:
INSERT INTO "users" ("name","last_name") VALUES (?,?) [42102-166]

**Comment by fernandezpablo85** [comment]
Try with:

``` scala
Users.ddl.create
```

Before calling insert.

**Comment by fernandezpablo85** [comment]
PS: The example assumes that your table exists
